# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
# Copy application code including README to satisfy setuptools if needed
COPY . .
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["python", "server.py"]
